version: "2.3"
services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "8080:8080"

  wyun:
    build:
      context: .
      dockerfile: build/wyun/Dockerfile
    tty: true
