version: "2.3"
services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "8080:8080"

  wyun:
    platform: linux/arm64/v8
    volumes:
      - ~/.ssh:/root/.ssh
    build:
      context: .
      dockerfile: build/wyun/Dockerfile
    tty: true

  db:
    volumes:
      - ./build/db/db:/docker-entrypoint-initdb.d
    image: mysql:oracle
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root